/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;
import Business.Customer.Customer;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientAppointmentWorkRequest;
import Business.WorkQueue.PatientOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JFrame;  
import javax.swing.SwingUtilities;  
  
import org.jfree.chart.ChartFactory;  
import org.jfree.chart.ChartPanel;  
import org.jfree.chart.JFreeChart;  
import org.jfree.data.category.DefaultCategoryDataset; 
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import org.jfree.chart.ui.ApplicationFrame;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author anushka
 */
public class GraphJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GraphJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Customer customer;
    public GraphJPanel(JPanel userProcessContainer, EcoSystem ecosystem ) {
      initComponents();
      this.userProcessContainer = userProcessContainer;        
//        this.userAccount = account;
      this.ecosystem = ecosystem;
      
      SwingUtilities.invokeLater(() -> {  
      PieChart_AWT example = new PieChart_AWT("Pie Chart");  
      example.setAlwaysOnTop(true);  
      example.pack();  
      example.setSize(600, 400);  
      
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
      
      //example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);  
    });  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
 
 
  
  public class PieChart_AWT extends ApplicationFrame {
   
   public PieChart_AWT( String title ) {
      super( title ); 
      setContentPane(createDemoPanel( ));
   }
   
   
   
   private PieDataset createDataset( ) {
      int orderedQuantity = 0;
      int apptQuantity = 0;
      for(Customer c : ecosystem.getCustomerDirectory().getCustomerList()){
          for(WorkRequest wr : c.getUserAccount().getWorkQueue().getWorkRequestList()){
              if(wr instanceof PatientAppointmentWorkRequest){
                  apptQuantity += ((PatientAppointmentWorkRequest) wr).getQuantity();
              }
              if(wr instanceof PatientOrderWorkRequest){
                  orderedQuantity += ((PatientOrderWorkRequest) wr).getQuantity();
              }
          }
      } 
       
       
      DefaultPieDataset dataset = new DefaultPieDataset( );
      dataset.setValue( "Supplied Doses" , orderedQuantity );  
      dataset.setValue( "Administered Doses" , apptQuantity );   
      return dataset;         
   }
   
   private JFreeChart createChart( PieDataset dataset ) {
      JFreeChart chart = ChartFactory.createPieChart(      
         "Patient Requests",   // chart title 
         dataset,          // data    
         true,             // include legend   
         true, 
         false);

      return chart;
   }
   
   public JPanel createDemoPanel( ) {
      JFreeChart chart = createChart(createDataset( ) );  
      return new ChartPanel( chart ); 
   }

   
   }
}
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

