/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.LabSupervisor.LabSupervisor;
import Business.LabTechnician.LabTechnician;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabApprovalWorkRequest;
import java.awt.CardLayout;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.mail.Message;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.LoginScreen;

/**
 *
 * @author anushka
 */
public class CustomerSignupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSignupJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Customer customer;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public CustomerSignupJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;        
        this.userAccount = new UserAccount();
        this.ecosystem = ecosystem;
        ecosystem = dB4OUtil.retrieveSystem();
        populateLabsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPtnName = new javax.swing.JTextField();
        txtPtnAddress = new javax.swing.JTextField();
        txtPtnCommunity = new javax.swing.JTextField();
        txtPtnZip = new javax.swing.JTextField();
        txtPtnAge = new javax.swing.JTextField();
        txtPtnDiabetesType = new javax.swing.JTextField();
        txtPtnGlucoseLvl = new javax.swing.JTextField();
        txtPtnPhoneNum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPtnUsername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCreatePtn = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        txtPtnPassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLabs = new javax.swing.JTable();

        jLabel1.setText("Name");

        jLabel2.setText("Address");

        jLabel3.setText("Community");

        jLabel4.setText("Zip");

        jLabel5.setText("Age");

        jLabel6.setText("Diabetes Type");

        jLabel7.setText("Glucose Level");

        jLabel8.setText("Phone Number");

        txtPtnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPtnNameActionPerformed(evt);
            }
        });

        jLabel9.setText("Username");

        txtPtnUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPtnUsernameActionPerformed(evt);
            }
        });

        jLabel10.setText("Password");

        btnCreatePtn.setText("Signup");
        btnCreatePtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePtnActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblLabs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Lab Name", "Lab Address"
            }
        ));
        jScrollPane1.setViewportView(tblLabs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnCreatePtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPtnGlucoseLvl)
                    .addComponent(txtPtnDiabetesType, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPtnAge, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPtnZip, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPtnCommunity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPtnAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPtnName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPtnUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txtPtnPhoneNum)
                    .addComponent(txtPtnPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPtnUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPtnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPtnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPtnAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPtnCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPtnZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPtnAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPtnDiabetesType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtPtnGlucoseLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtPtnPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnCreatePtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPtnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPtnNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPtnNameActionPerformed

    private void txtPtnUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPtnUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPtnUsernameActionPerformed

    private void btnCreatePtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePtnActionPerformed
        // TODO add your handling code here:
        if(txtPtnName.getText().isEmpty() || txtPtnPhoneNum.getText().isEmpty() || txtPtnAddress.getText().isEmpty() || 
           txtPtnUsername.getText().isEmpty() || txtPtnPassword.getText().isEmpty() ||
                txtPtnAge.getText().isEmpty() || txtPtnCommunity.getText().isEmpty() ||
                txtPtnDiabetesType.getText().isEmpty() || txtPtnGlucoseLvl.getText().isEmpty() ||
                txtPtnZip.getText().isEmpty()
                ) {
            JOptionPane.showMessageDialog(this, "Please fill all details.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int selectedRow = tblLabs.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        LabSupervisor ls = (LabSupervisor) tblLabs.getValueAt(selectedRow, 0);
        
        
        String name = txtPtnName.getText();
        long phonenumber = Long.parseLong(txtPtnPhoneNum.getText());
        String address = txtPtnAddress.getText();        
        String username = txtPtnUsername.getText();
        String password = String.valueOf(txtPtnPassword.getPassword());
        String community = txtPtnCommunity.getText();
        String diabetestype = txtPtnDiabetesType.getText();
        int glucoselvl = Integer.parseInt(txtPtnGlucoseLvl.getText());
        String zip = txtPtnZip.getText();
        int age = Integer.parseInt(txtPtnAge.getText());
        
        
        
        
        if(!ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(username)){
            JOptionPane.showMessageDialog(null, "Username already exists, select a new username", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
//        
//        Employee employee = ecosystem.getEmployeeDirectory().createEmployee(name);       
//        UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(username, password, employee, new CustomerRole());        
        Customer c = ecosystem.getCustomerDirectory().addCustomer(name, age, address, 
                                                            community, zip, "sk", phonenumber, glucoselvl, diabetestype, null);
        
        LabApprovalWorkRequest req = new LabApprovalWorkRequest();
        req.setCustomer(c);
        req.setMessage("Request to be reviewed");
        req.setReceiver(ls.getUserAccount());
        req.setStatus("PENDING");
        req.setPassword(password);
        req.setUsername(username);
        ls.getUserAccount().getWorkQueue().getWorkRequestList().add(req);
        
        JOptionPane.showMessageDialog(null, "Your Req is sent to your Lab for review.");
        
                
        txtPtnAddress.setText("");
        txtPtnAge.setText("");
        txtPtnCommunity.setText("");
        txtPtnDiabetesType.setText("");
        txtPtnGlucoseLvl.setText("");
        txtPtnName.setText("");
        txtPtnPassword.setText("");
        txtPtnPhoneNum.setText("");
        txtPtnUsername.setText("");
        txtPtnZip.setText("");
        populateLabsTable();
        
        
        
        
                                                         
//        txtName.setText("");
//        txtMobile.setText("");
//        txtAddress.setText("");
//        txtUsername.setText("");
//        txtPassword.setText("");
//        populateTable();
        JOptionPane.showMessageDialog(null, "Customer Created");
        
        
    }//GEN-LAST:event_btnCreatePtnActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        JPanel blankJP = new JPanel();
        LoginScreen ls = new LoginScreen(userProcessContainer, ecosystem);
        userProcessContainer.add("blank", ls);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_btnLogoutActionPerformed


    public void populateLabsTable(){
        DefaultTableModel model = (DefaultTableModel) tblLabs.getModel();
        model.setRowCount(0);
        if(ecosystem.getLabSupervisorDirectory().getLabSupervisorList().size() == 0) return;
        for (LabSupervisor ls : ecosystem.getLabSupervisorDirectory().getLabSupervisorList()) {
            Object[] row = new Object[2];
            row[0] = ls;
            row[1] = ls.getUserAccount().getUsername();
            
            model.addRow(row);       
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePtn;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLabs;
    private javax.swing.JTextField txtPtnAddress;
    private javax.swing.JTextField txtPtnAge;
    private javax.swing.JTextField txtPtnCommunity;
    private javax.swing.JTextField txtPtnDiabetesType;
    private javax.swing.JTextField txtPtnGlucoseLvl;
    private javax.swing.JTextField txtPtnName;
    private javax.swing.JPasswordField txtPtnPassword;
    private javax.swing.JTextField txtPtnPhoneNum;
    private javax.swing.JTextField txtPtnUsername;
    private javax.swing.JTextField txtPtnZip;
    // End of variables declaration//GEN-END:variables
}
